services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - dockernet
    depends_on:
      - php
      - db

  php:
    build:
      context: ./.docker
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    expose:
      - "9000"
    networks:
      - dockernet
    ports:
      - "9003:9003"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gentilcred
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/initdb:/docker-entrypoint-initdb.d
      - ./.docker/mysql/:/dump
      - ./.docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - dockernet

networks:
  dockernet:

volumes:
  db-data:
